# -*- coding: utf-8 -*-
"""scraping data ulasan shopee.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QMyZCnzUIavNwqVrfqMBv4E3xSOWptkf
"""

import re
import requests
import pandas as pd
import time

# Ganti dengan cookie dari browser
cookies = {
    "SPC_EC": ".bFVHRktOTVJOSVRvT3ZhZfzPcfgOtdAJDQjwjyUIvuFqJ/k6xVcsd6wSqS5O8urX7TM5SF6ir94g6ZeffTgX9P/ybxfq6JAq41azwi22RyZtCnS2HB9PpT/v7zh73uRi0/+GQon/jsIx3SCE1JT9Aml2pD4AbghLkSSBOuLZ09jBRonANIAnab3BzlH1AOIY09gj64j2IjvzmPUgl+VMfJxEuHzElOqKZRM6oio3Dz+fRWaxVXsB0iV3TbjTFODK",
    "SPC_R_T_ID": "Pu5Dh3hwEWBfZOp7anFD4anCyH4LltQ+J+DvlnjDppQyYHmAQ83SjRqHLK1a5bfiRBbszz/1nFh85nDHNLy3YvWXH0xYHMW8wh5czGVqxLY84ovs1llRERTDs5FIZhMyr8uVUlULi1lFEJxM4pjTS3xxycZme3GrKceNTp0yD6A="
}

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
}

urls = [
    'https://shopee.co.id/Hongzhuo-Cookware-Panci-Set-Wajan-Penggorengan-Spatula-Set-Isi-13Pcs-1-Set-Frypan-Saucepan-i.263338737.6195214203',
    'https://shopee.co.id/Hongzhuo-Panci-Set-Isi-6pcs-Pot-Series-Panci-Terlengkap-dengan-Tutupan-dan-Spatula-i.263338737.16914282677',
    'https://shopee.co.id/Hongzhuo-Panci-Sop-22cm-Enamel-Stainless-Soup-Pot-Panci-Susu-i.263338737.16027427773',
    'https://shopee.co.id/product/263338737/23740919762',
    'https://shopee.co.id/product/263338737/18244857852',
    'https://shopee.co.id/product/263338737/24601642262'
]

ratings_url = 'https://shopee.co.id/api/v2/item/get_ratings?filter=0&flag=1&itemid={item_id}&limit=20&offset={offset}&shopid={shop_id}&type=0'

# Ekstrak shop_id dan item_id dari semua URL
id_pairs = []
for url in urls:
    r = re.search(r'i\.(\d+)\.(\d+)', url) or re.search(r'product/(\d+)/(\d+)', url)
    if r:
        shop_id, item_id = r[1], r[2]
        id_pairs.append((shop_id, item_id))

# Siapkan wadah data
data = {'username': [], 'rating': [], 'comment': []}
max_reviews = 1500
total_reviews = 0

def scrape(shop_id, item_id):
    global total_reviews
    offset = 0
    while total_reviews < max_reviews:
        url = ratings_url.format(shop_id=shop_id, item_id=item_id, offset=offset)
        res = requests.get(url, headers=headers, cookies=cookies)
        print(f"Scraping item {item_id} offset {offset} - Status: {res.status_code}")

        if res.status_code != 200:
            print("Gagal ambil data.")
            break

        result = res.json()
        ratings = result.get('data', {}).get('ratings', [])

        if not ratings:
            break

        for rate in ratings:
            comment = rate.get('comment')
            if comment:
                data['username'].append(rate.get('author_username', 'N/A'))
                data['rating'].append(rate.get('rating_star', 0))
                data['comment'].append(comment)
                total_reviews += 1

        if len(ratings) < 20:
            break

        offset += 20
        time.sleep(1)

# Mulai scraping semua produk
for shop_id, item_id in id_pairs:
    scrape(shop_id, item_id)
    if total_reviews >= max_reviews:
        break

# Simpan ke file CSV
df = pd.DataFrame(data)
df.to_csv('shopee_reviews_filtered.csv', index=False)
print(f"\nTotal review berhasil disimpan: {len(df)}")